/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Buy me a coffee": "请我喝杯咖啡",
    "Change Log": "更新日志",
    "Codex": "图鉴",
    "Enjoying the game?": "喜欢这个游戏吗？",
    "High Score": "最高分",
    "Initialize Defense": "初始化防御",
    "Last Wave": "最后一波",
    "Offline Mode (Local)": "离线模式（本地）",
    "Ranking": "排名",
    "Stack upgrades. Survive the void.": "堆叠升级。在虚空中生存。",
    "SURVIVORS": "幸存者",
    "The Infinite Spire": "无限尖塔",
    "TOWER": "塔",
    "Tutorial": "教程",
    "POISON": "毒",
    "POI": "毒",
    "PHY": "物理",
    "PHYSICAL": "物理",
    "MAGIC": "魔法",
    "MAG": "魔法",
    "ICE": "冰",
    "FIRE": "火",
    "FIR": "火",
    "DMG": "伤害",
    "✕ CLOSE": "✕ 关闭",
    "* Costs shown are Base Costs. Prices increase exponentially for each upgrade of the same type you own.": "* 所示成本为基础成本。你拥有的相同类型的每一次升级，价格都会呈指数级增长。",
    "| Radius:": "| 速率:",
    "Base Dmg:": "基础伤害:",
    "Base Cost": "基础成本",
    "Basic Fire damage.": "基础 火焰 伤害.",
    "Basic Ice damage.": "基础 冰霜 伤害.",
    "Basic Magic damage.": "基础 魔法 伤害.",
    "Basic Physical damage.": "基础 物理 伤害.",
    "Enemies": "敌人",
    "HEALER": "治疗者",
    "Heavy Poison damage.": "重型 毒药 伤害.",
    "System": "系统",
    "TANK": "坦克",
    "TIER": "层级",
    "TYPE": "类型",
    "Speed:": "速度:",
    "Type:": "类型:",
    "Cooldown:": "冷却时间:",
    "Upgrades": "升级",
    "Tower Modules": "塔模块",
    "RUNNER": "奔跑者",
    "RNG": "奔跑者",
    "WORM": "蠕虫",
    "Power Core": "力量核心",
    "BOSS": "BOSS",
    "CD": "冷却时间",
    "Modules": "模块",
    "GRUNT": "咕哝",
    "Nano Repair": "纳米修复",
    "Void Miner": "虚空矿工",
    "Void Codex": "虚空图鉴",
    "Void Rift": "虚空裂隙",
    "FRACTAL": "分形",
    "Chaos Bolt": "混乱之箭",
    "CHA": "混乱之箭",
    "Active Weapons Array": "主动武器阵列",
    "Apex Threats": "顶级威胁",
    "Arcane Orb": "奥术宝珠",
    "Arrow Module": "箭头模块",
    "Astral Ring": "星体环",
    "Ballista": "弩车",
    "Bio-Hazard Mortar": "生物危害砂浆",
    "Blast Cannon": "爆破炮",
    "BROODMOTHER": "母体",
    "Cluster Bomb": "集束炸弹",
    "Creates a wide orbiting sphere of pure magic energy. High DPS.": "创造一个巨大的轨道球体，充满纯魔法能量。高输出。",
    "Cryo Beam": "低温光束",
    "Deals 1.0x damage to ALL types. Ignores resistances.": "对所有类型造成1.0倍伤害。无视抵抗。",
    "Deals Fire AOE damage.": "造成火焰范围伤害。",
    "DISRUPTOR": "破坏者",
    "Economy": "经济",
    "Ember Coil": "余烬线圈",
    "Entropy Ray": "熵射线",
    "Fire AOE that hits hard.": "火系大范围攻击。",
    "Fires a large bolt that pierces through enemies.": "射出一个巨大的弩箭，可以穿透敌人。",
    "Freezes enemies instantly.": "瞬间冻结敌人。",
    "Frost Shard": "冰霜碎片",
    "Generates +1 Gold per second.": "每秒生成+1金币。",
    "Hellfire Stream": "地狱火流",
    "High Magic damage, medium range.": "高魔法伤害，中距离。",
    "High Physical damage, extreme range.": "高物理伤害，范围极广。",
    "Ice damage that slows enemies.": "使敌人减速的冰伤害。",
    "Increases damage of ALL types by 2.5%.": "增加所有类型伤害2.5%。",
    "Increases fire rate by 10%.": "增加10%的射速。",
    "Increases gold from enemies by 15%.": "增加15%来自敌人的金币。",
    "Increases range by 10%. Max 50%.": "射程增加10%。最多50%。",
    "LEGENDARY": "传说",
    "LEGENDARY. Launches a rift at the strongest enemy on screen. Massive AOE.": "传说。向屏幕上最强的敌人发射一道裂缝。巨大的效果范围。",
    "LEGENDARY. Short range spikes in 8 directions. Upgrades increase damage.": "传说。8个方向的短程尖峰。升级会增加伤害。",
    "LEGENDARY. Unleashes a continuous stream of fire. Short range.": "传说。释放出连续的火焰流。近距离。",
    "Low damage, but pushes enemies away forcibly.": "低伤害，但强行推开敌人。",
    "Magic Missile": "魔法飞弹",
    "Manage targeting priority for each weapon type independently.": "独立管理每种武器类型的瞄准优先级。",
    "Nanofiber Weave": "纳米纤维织物",
    "NEAREST": "最近的",
    "Omni-Spikes": "全能尖刺",
    "ORBITER": "轨道飞行器",
    "Overclocker": "超频器",
    "Permafrost": "永久冻土",
    "Piercing beam of Chaos damage. Effective against all.": "混沌穿透光束伤害。对所有人都有效。",
    "Poison damage over time.": "随时间增加毒素伤害。",
    "Railgun": "轨道炮",
    "Range:": "范围:",
    "Regenerates +0.5 Tower HP per second.": "每秒回复0.5塔的生命值。",
    "Repulsor Plate": "反流板",
    "Resistant To": "抵抗",
    "Restores 100 HP to the tower.": "为塔恢复100点生命值。",
    "Scavenger Protocol": "清道夫协议",
    "STALKER": "跟踪狂",
    "Standard Threats": "标准威胁",
    "SWARMER": "游动孢子",
    "Target Priority": "目标优先顺序",
    "Targeting Lens": "瞄准镜头",
    "Venom Sprayer": "毒液喷射器",
    "Weak To": "弱到",
    "⟳ Reroll": "⟳ 重掷",
    "ABORT": "中止",
    "GOLD": "金币",
    "Good Luck": "祝你好运",
    "GPS": "金币每秒",
    "Next": "下一个",
    "No records found.": "没有找到记录。",
    "Score": "分数",
    "SCORE": "分数",
    "SPD": "速度",
    "Skip": "跳过",
    "Secure Transmission": "安全传输",
    "REFRESH:": "刷新:",
    "Resource Management": "资源管理",
    "System Output": "系统输出",
    "System Integrity": "系统完整性",
    "Prev": "上一个",
    "x SPEED": "x 速度",
    "Void Market": "虚空市场",
    "The Void Market": "虚空市场",
    "Upgrade Database": "升级数据库",
    "Tech Tree": "科技树",
    "Targeting Logic": "目标逻辑",
    "Buy me a coffee →": "请作者喝杯咖啡 →",
    "CODEX & MODULES": "图鉴 & 模块",
    "Codex Access": "访问图鉴",
    "Active Modules": "活动模块",
    "BOUNTY": "赏金",
    "Browse all potential upgrades, including their stats and tier rarity. Plan your build strategy here.": "浏览所有潜在的升级，包括他们的属性和等级稀有性。在这里规划您的构建策略。",
    "CRITICAL: You can customize targeting priorities for each weapon type. Switch high-damage weapons to 'Strongest' or rapid-fire to 'Nearest' to maximize efficiency.": "关键：你可以为每种武器定制目标优先级。将高伤害武器切换为“最强”或将速射切换为“最近”以最大化效率。",
    "Defense Protocol Initialized": "防御协议初始化",
    "Elite": "精英",
    "Elite Hostiles": "精英敌人",
    "Enemy Database": "敌人数据库",
    "High Command Records": "最高指挥纪录",
    "High-threat Elite enemies are identified by a pulsing golden aura. They are tougher and deal more damage, but yield triple rewards.": "高威胁的精英敌人是由一个脉冲的金色光环识别。他们更强硬，造成更多伤害，但会产生三倍的奖励。",
    "INTEGRITY": "完整性",
    "Inventory Depleted": "库存耗尽",
    "Monitor your Tower's HP and vital statistics in the System Output panel. Critical damage will be indicated here.": "在系统输出面板中监控塔的HP和重要统计数据。临界伤害将在这里显示。",
    "Open the Tech Tree to unlock powerful active abilities and permanent passive scaling stats.": "打开科技树可以解锁强大的主动技能和永久的被动缩放属性。",
    "Purchase upgrade modules here. Modules stack infinitely to increase your power. Warning: The shop rotates every 20 seconds.": "此处购买升级模块。模块无限堆叠以增加您的功率。警告：商店每20秒旋转一次。",
    "Tech Tree Access": "科技树访问",
    "The Codex is your central database for enemy intelligence, upgrade details, and weapon configuration.": "法典是敌人情报、升级细节和武器配置的中央数据库。",
    "The void adapts. Stay vigilant.": "虚空适应了。保持警惕。",
    "Time Dilation": "时间膨胀",
    "Toggle between 1x and 2x speed to accelerate time during slow waves. Use with caution.": "在1倍和2倍的速度之间切换，以在慢波期间加速时间。请谨慎使用。",
    "Track your current Gold and Score here. You earn Gold by destroying enemies.": "跟踪您当前的金币和得分在这里。你可以通过消灭敌人来获得金币。",
    "View detailed stats, resistances, and weaknesses for all known void entities. Knowing your enemy is key to survival.": "查看所有已知虚空实体的详细统计、抗性和弱点。了解敌人是生存的关键。",
    "View your currently installed weapon modules here. This overview shows your exact loadout.": "查看当前安装的武器模块。这个概览显示了您的确切负载。",
    "Welcome to the Spire. Your objective is to defend the central tower against infinite waves of void entities.": "欢迎来到尖塔。你的目标是保护中央塔免受无限波的虚空实体。",
    "Close": "关闭",
    "Records are synchronized globally.": "记录是全球同步的。",
    "Leaderboard": "排行榜",
    "Global Defense Rankings": "全球防御排行榜",
    "Audio": "音频",
    "System Update History": "系统更新历史",
    "Latest Release": "最近发布",
    "Added a new tower targeting option: Fastest in Range.": "增加了一个新的塔瞄准选项：最快在范围内。",
    "Additional small UI polish across menus and in-game HUD.": "在菜单和游戏内HUD上进行额外的小UI优化。",
    "Astral Ring module fully reworked; its effect now functions correctly and scales as intended.": "星体环模块完全重做；它的效果现在可以正常运行，并按预期缩放。",
    "Balance & Gameplay Adjustments": "平衡和玩法调整",
    "Damage percentage upgrade tiers adjusted for smoother scaling and reduced overpowered builds.": "伤害百分比升级等级调整平滑缩放和减少过度强大的建设。",
    "Fixed a potentially game-breaking bug involving healer enemies.": "修复了一个涉及治疗敌人的潜在游戏破坏bug。",
    "Health numbers now display alongside the health bar for better readability.": "为了更好的可读性，现在生命值显示在生命条旁边。",
    "Increased various text sizes to improve visibility.": "增加了各种文本大小以提高可见性。",
    "Legendary module drop rate rebalanced to make them less common and better aligned with intended progression.": "传奇模块的掉落率重新平衡，使它们不那么常见，并更好地与预期的进程保持一致。",
    "Slightly adjusted several sound effects for clarity and overall polish.": "稍微调整了几个声音效果的清晰度和整体抛光。",
    "UI Improvements": "UI的改进",
    "Gold": "金币",
    "CHAOS": "混乱",
    "Unlock": "解锁",
    "Wave": "波次",
    "Lvl": "等级",
    "Modules:": "模块:",
    "Return": "返回",
    "Resources": "资源",
    "AEGIS": "宙斯盾",
    "LONGSHOT": "远射",
    "OBLITERATE": "抹杀",
    "OVERCLOCK": "超频",
    "Cooldown": "冷却时间",
    "Current Damage Bonus": "当前伤害加成",
    "Duration": "持续时间",
    "UPGRADE TO +": "升级到 +",
    "Active Protocols": "活动协议",
    "Arcane Resonance": "奥术共鸣",
    "Cryo Resonance": "低温共鸣",
    "Deploys an impenetrable shield around the tower for 5 seconds.": "在塔周围部署一个坚不可摧的护盾，持续5秒。",
    "Detonates a localized void bomb. Wipes all non-boss enemies. Heavily damages bosses. SINGLE USE PER RUN.": "引爆一个局部的虚空炸弹。清除所有非boss敌人。严重伤害boss。每次使用一次。",
    "Doubles tower attack speed and damage for 10 seconds.": "塔的攻击速度和伤害增加一倍，持续10秒。",
    "Doubles tower range for 15 seconds.": "塔的范围翻倍，持续15秒。",
    "Elemental Resonances (Infinite Scaling)": "元素共鸣（无限缩放）",
    "Entropy Resonance": "熵共鸣",
    "Instant": "即时",
    "Kinetic Resonance": "动力学共鸣",
    "Once per run": "每次运行一次",
    "The ground trembles.": "大地在颤抖。",
    "The silence is deafening.": "寂静震耳欲聋。",
    "The Spire awakens...": "尖塔觉醒了...",
    "Thermal Resonance": "热共鸣",
    "Toxin Resonance": "毒素共鸣",
    "Unlock protocols and amplify elemental resonance.": "解锁协议，放大元素共鸣。",
    "No escape.": "无处可逃。",
    "A chill wind blows from the abyss.": "一阵寒风从深渊吹来。",
    "Protect the core at all costs.": "不惜一切代价保护核心。",
    "READY": "就绪",
    "Reboot System": "重启系统",
    "\"The Infinite Spire remains... you do not.\"": "“无限尖塔依然存在...你没有。\”",
    "Another wave breaks against the walls.": "另一波打破墙壁。",
    "Casualty Report": "伤亡报告",
    "Critical Failure": "临界故障",
    "DEPLETED": "耗尽",
    "Download Backup (.json)": "下载备份（.json）",
    "Entropy increases.": "熵值增加。",
    "Final Score": "最终得分",
    "Main Menu": "主菜单",
    "PIERCE": "穿刺",
    "Power levels fluctuating.": "能量水平波动。",
    "RECHARGING": "充电",
    "Record Archived": "记录已存档",
    "Record your legacy": "记录你的遗产",
    "Relentless.": "无情。",
    "Shadows lengthen around the spire.": "尖塔周围的影子拉长了。",
    "Signal Lost at Wave": "信号丢失在波",
    "Signal lost...": "信号丢失...",
    "System Configuration": "系统配置",
    "System Online": "系统在线",
    "The Infinite Spire endures.": "无限尖塔经久不衰。",
    "The swarm approaches.": "蜂群靠近了。",
    "They adapt.": "他们适应了。",
    "They are coming.": "他们来了。",
    "Darkness gathers.": "黑暗聚集。",
    "Geometric shapes screech in the distance.": "几何图形在远处发出刺耳的声音。",
    "The void hungers...": "虚空饥饿...",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "LGD": "LGD",
    "Gityx": "Gityx",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "☕": "☕",
    "": "",
    "%)": "%)",
    "(+": "(+",
    "↻": "↻",
    "/": "/",
    "%": "%",
    "/s": "/秒",
    "#": "#",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Version ": "版本 ",
    "Protocol: ": "协议: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (Demo)": " (演示版)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);